### ISSUE TITLE
Curious about RaftKeeper and CH-keeper's performance with the newest version

### ISSUE THREAD

**Issue by taiyang-li** [azat/keeper-zookeeper#2]
Now the newest version of CH-Keeper is 24.6, and for RaftKeeper it is v2.1.0. Just curious about RaftKeeper and CH-keeper's performance with the newest version.

**Comment by azat** [comment]
New numbers - https://github.com/azat/keeper-zookeeper/commit/9f1d449fa9bf74f11bfae258472fa1e53ba286dc
